# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# Facebook
[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://x.com/irmasman22garut"

[social.params]
icon = "brand-facebook"

# Instagram
[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/irmasman22garut_official"

[social.params]
icon = "brand-instagram"

# TikTok
[[social]]
identifier = "tiktok"
name = "TikTok"
url = "https://tiktok.com/@irmasman22garut_official"

[social.params]
icon = "brand-tiktok"

# X
[[social]]
identifier = "x"
name = "X"
url = "https://x.com/irmasman22garut"

[social.params]
icon = "brand-x"
