name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0  # fetch all history for .GitInfo and .Lastmod
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2 
        with:
          go-version: '1.22'
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Replace title
        run: |
          # Pages
          sed -i 's@<title>Arsip</title>@<title>Arsip - Blog IRMA Baitussalam</title>@g' ./public/arsip/index.html
          sed -i 's@content="Arsip"@content="Arsip - Blog IRMA Baitussalam"@g' ./public/arsip/index.html
          sed -i 's@<title>Cari</title>@<title>Cari - Blog IRMA Baitussalam</title>@g' ./public/cari/index.html
          sed -i 's@content="Cari"@content="Cari - Blog IRMABaitussalam"@g' ./public/cari/index.html
          sed -i 's@<title>Tag</title>@<title>Tag - Blog IRMA Baitussalam</title>@g' ./public/tags/index.html
          sed -i 's@content="Tag"@content="Tag - Blog IRMABaitussalam"@g' ./public/tags/index.html
          sed -i 's@<title>Tag</title>@<title>Tag - Blog IRMA Baitussalam</title>@g' ./public/tags/page/*/index.html
          sed -i 's@content="Tag"@content="Tag - Blog IRMABaitussalam"@g' ./public/tags/page/*/index.html
          sed -i 's@<title>Kategori</title>@<title>Kategori - Blog IRMA Baitussalam</title>@g' ./public/categories/index.html
          sed -i 's@content="Kategori"@content="Kategori - Blog IRMABaitussalam"@g' ./public/categories/index.html
          sed -i 's@<title>Halaman</title>@<title>Halaman - Blog IRMA Baitussalam</title>@g' ./public/page/index.html
          sed -i 's@content="Halaman"@content="Halaman - Blog IRMABaitussalam"@g' ./public/page/index.html
          sed -i 's@<title>Postingan</title>@<title>Postingan - Blog IRMA Baitussalam</title>@g' ./public/post/index.html
          sed -i 's@content="Postingan"@content="Postingan - Blog IRMABaitussalam"@g' ./public/post/index.html

          # Category
          folder=(`ls ./public/kategori`)
          for d in "${folder[@]}"; do
            if [[ -d "./public/kategori/$d" && "$d" != "page" ]]; then
              sed -i 's@Category:@Kategori:@g' ./public/kategori/$d/index.html
              sed -i 's@Blog - IRMA@Blog IRMA@g' ./public/kategori/$d/index.html
              fi
          done

          # Tags
          folder=(`ls ./public/tags`)
          for d in "${folder[@]}"; do
            if [[ -d "./public/tags/$d" && "$d" != "page" ]]; then
              sed -i 's@Tags:@Tag:@g' ./public/tags/$d/index.html
              sed -i 's@Blog - IRMA@Blog IRMA@g' ./public/tags/$d/index.html
            fi
          done
      - name: Moved folder names
        run: |
          cp -rf ./public/categories/* ./public/kategori
          rm -rf ./public/categories/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa #v3.0.1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
